# Generated by Django 6.0.6 on 2026-06-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking', models.CharField(blank=True, max_length=50, null=True)),
                ('has_commission_agreement', models.BooleanField(default=False)),
                ('commission_type', models.CharField(default='None', max_length=25)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('commission_currency', models.CharField(default='GBP', max_length=3)),
                ('commission_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('admissions_portal_url', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['university_name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_code', models.CharField(max_length=20, unique=True)),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(default='Agent', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('default_commission_type', models.CharField(default='Percentage of University Commission', max_length=40)),
                ('default_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_currency', models.CharField(default='BDT', max_length=3)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_routing_no', models.CharField(blank=True, max_length=30, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_document', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['partner_name'],
            },
        ),
    ]
