# Generated by Django 6.0.6 on 2026-06-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='year',
            field=models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='programme',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='programme',
            field=models.ForeignKey(db_column='programme_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.programme'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='programme',
            field=models.ForeignKey(db_column='programme_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.programme'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('year', 'period_number', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'attendance_date', 'session_type')},
        ),
    ]
