# Generated by Django 6.0.6 on 2026-06-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=30, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated value at end of useful life', max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current book value (purchase - accumulated depreciation)', max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation_method', models.CharField(choices=[('Straight Line', 'Straight Line'), ('Declining Balance', 'Declining Balance'), ('None', 'No Depreciation')], default='Straight Line', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location (Room 201, 2nd Floor, etc.)', max_length=200, null=True)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Damaged', 'Damaged')], default='Good', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Disposed', 'Disposed'), ('Lost', 'Lost'), ('Retired', 'Retired')], default='Active', max_length=55)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.branch')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='hrm.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_assets', to='accounting.voucher')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition_at_assignment', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=15)),
                ('condition_at_return', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Returned', 'Returned'), ('Transferred', 'Transferred')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hrm.employee')),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation percentage (e.g. 20.00 = 20%)', max_digits=5)),
                ('useful_life_years', models.IntegerField(default=5, help_text='Useful life in years')),
                ('status', models.CharField(default='Active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coa_asset_account', models.ForeignKey(blank=True, help_text='Asset account in COA (e.g. 1210 Office Equipment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_asset', to='accounting.chartofaccount')),
                ('coa_depreciation_account', models.ForeignKey(blank=True, help_text='Accumulated depreciation account (e.g. 1211)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_depreciation', to='accounting.chartofaccount')),
                ('coa_expense_account', models.ForeignKey(blank=True, help_text='Depreciation expense account (e.g. 5701)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_category_expense', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assetcategory'),
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Emergency', 'Emergency'), ('Upgrade', 'Upgrade')], default='Preventive', max_length=15)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=52)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.asset')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_done', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.voucher')),
            ],
            options={
                'db_table': 'asset_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('depreciation_id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField()),
                ('period_label', models.CharField(help_text='e.g. "June 2026" or "2025-2026"', max_length=20)),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Calculated', 'Calculated'), ('Posted', 'Posted'), ('Reversed', 'Reversed')], default='Calculated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='core.asset')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.voucher')),
            ],
            options={
                'db_table': 'asset_depreciation',
                'ordering': ['-depreciation_date'],
                'unique_together': {('asset', 'period_label')},
            },
        ),
    ]
