# Generated by Django 6.0.6 on 2026-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('coa_id', models.AutoField(primary_key=True, serialize=False)),
                ('coa_code', models.CharField(max_length=10, unique=True)),
                ('coa_name', models.CharField(max_length=200)),
                ('parent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(max_length=9)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_cash_account', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='Active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'ordering': ['coa_code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('receivable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('new_admissions', models.IntegerField(default=0)),
                ('total_collections', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='LateFeeCharge',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_date', models.DateField()),
                ('days_overdue', models.IntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='Calculated', max_length=9)),
                ('waive_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'late_fee_charges',
            },
        ),
        migrations.CreateModel(
            name='MainLedger',
            fields=[
                ('ledger_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_type', models.CharField(max_length=30)),
                ('reference_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'main_ledger',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('amount_in_bdt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=15)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'payment_items',
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('cash_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('given_to', models.CharField(blank=True, max_length=150, null=True)),
                ('received_from', models.CharField(blank=True, max_length=150, null=True)),
                ('receipt_attached', models.BooleanField(default=False)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'petty_cash',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeFeeHead',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_installable', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'programme_fee_heads',
            },
        ),
        migrations.CreateModel(
            name='StudentLedger',
            fields=[
                ('s_ledger_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('particulars', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_ledger',
                'ordering': ['entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('narration', models.TextField()),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vouchers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'voucher_entries',
            },
        ),
    ]
