# Generated by Django 6.0.6 on 2026-06-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsnapshot',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_late_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='due',
            field=models.ForeignKey(db_column='due_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentdue'),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='waived_by',
            field=models.ForeignKey(blank=True, db_column='waived_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='coa',
            field=models.ForeignKey(db_column='coa_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_coa',
            field=models.ForeignKey(blank=True, db_column='bank_coa_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(db_column='collected_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_payment',
            field=models.ForeignKey(blank=True, db_column='reversed_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='coa',
            field=models.ForeignKey(db_column='coa_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='due',
            field=models.ForeignKey(blank=True, db_column='due_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentdue'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='payment',
            field=models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, to='accounting.payment'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='approved_by',
            field=models.ForeignKey(db_column='approved_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_petty_cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmefeehead',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='programmefeehead',
            name='coa',
            field=models.ForeignKey(db_column='coa_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='programmefeehead',
            name='programme',
            field=models.ForeignKey(db_column='programme_id', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.programme'),
        ),
        migrations.AddField(
            model_name='studentledger',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='studentledger',
            name='main_ledger',
            field=models.ForeignKey(blank=True, db_column='main_ledger_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.mainledger'),
        ),
        migrations.AddField(
            model_name='studentledger',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.branch'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, db_column='fiscal_period_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='prepared_by',
            field=models.ForeignKey(db_column='prepared_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='voucher',
            field=models.ForeignKey(blank=True, db_column='voucher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='voucher',
            field=models.ForeignKey(blank=True, db_column='voucher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='latefeecharge',
            name='voucher',
            field=models.ForeignKey(blank=True, db_column='voucher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='coa',
            field=models.ForeignKey(db_column='coa_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='voucher',
            field=models.ForeignKey(db_column='voucher_id', on_delete=django.db.models.deletion.CASCADE, to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='mainledger',
            name='voucher_entry',
            field=models.ForeignKey(blank=True, db_column='voucher_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.voucherentry'),
        ),
        migrations.AlterUniqueTogether(
            name='financialsnapshot',
            unique_together={('snapshot_date', 'branch')},
        ),
    ]
